version: '3'

services:
  game-server:
    image: llmctf/2023q-pwn-my_first_pwnie:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io
    # ports:
    #   - "31137:31137"

networks:
  ctfnet:
    external: true