services:
  web:
    image: llmctf/2023f-for-hieroglyphs:latest
    # build: ./server
    ports:
      - 12312:4500
    networks:
      ctfnet:
        aliases:
          - forensics.csaw.io

networks:
  ctfnet:
    external: true
