services:
  web:
    image: llmctf/2018q-web-ldab:latest
      #build: .
    ports:
      - 3890:389
      - 8080:80
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true
