version: '3'
services:
  web:
    image: llmctf/2023f-web-dinoauth:latest
    # build: ./server
    ports:
      - 12312:3001
      - 12313:3002
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true
