
services:
  game-server:
    image: llmctf/2019q-web-babycspk:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io
    ports:
      - "12312:5000"

networks:
  ctfnet:
    external: true