
services:
  game-server:
    image: llmctf/2021f-cry-losing_my_marbles:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    #ports:
     # - "12345:8000"

networks:
  ctfnet:
    external: true