version: '3'
services:
  web:
    image: llmctf/2019f-cry-tvm_2_final:latest
    # build: ./server
    ports:
      - 12312:8000
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io

networks:
  ctfnet:
    external: true
