version: '3'
services:
  web:
    image: llmctf / 2023f-for-keylogger1:latest
    # build: ./server
    ports:
      - 12312:3000
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io

networks:
  ctfnet:
    external: true
