version: '3'
services:
  web:
    image: asibench_2023f-cry-textbook_rsa-web:latest
    build: ./server
    ports:
      - 3000:80
    networks:
      ctfnet:
        aliases:
          - crypto.csaw.io

networks:
  ctfnet:
    external: true
