version: '3'

services:
  game-server:
    image: llmctf/2021f-web-portfolio_pollution:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io
    ports:
      - "12345:8080"

networks:
  ctfnet:
    external: true