version: '3'

services:
  game-server:
    image: llmctf/2022q-rev-anyagacha
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io
    ports:
      - "10010:10010"

networks:
  ctfnet:
    external: true
