services:
  web:
    image: llmctf/2019f-pwn-defile:latest
    # build: ./server
    ports:
      - 12312:8000
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true
