version: '3'

services:
  game-server:
    image: llmctf/2019q-cry-time_lie:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - "12312:5000"

networks:
  ctfnet:
    external: true