version: '3'
services:
  web:
    image: llmctf/2020q-web-flask_caching:latest
    # build: ./server
    ports:
      - 12380:5000
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true
