services:

  server:
    image: llmctf/2020f-web-comment_anywhere-server:latest
    build:
      context: ./server
    ports:
      - "12380:8000"
    networks:
      ctfnet:
        aliases:
          - server
          - comment-anywhere.chal.csaw.io

  admin:
    image: llmctf/2020f-web-comment_anywhere-admin:latest
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    networks:
      - ctfnet
    depends_on:
      server:
        condition: service_started

# External network ctfnet
networks:
  ctfnet:
    external: true
