version: '3'
services:
  web:
    image: llmctf/2020q-pwn-roppity:latest
    # build: ./server
    ports:
      - 12380:8000
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true
