
services:
  game-server:
    image: llmctf/2019q-web-unagi:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - ≈
    ports:
      - "12312:80"

networks:
  ctfnet:
    external: true