
services:
  game-server:
    image: llmctf/2019q-cry-fault_box:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - "12312:23333"

networks:
  ctfnet:
    external: true