version: '3'
services:
  web:
    image: llmctf/2018f-pwn-wic_wac_woe:latest
    ports:
      - 1337:8080
    networks:
      ctfnet:
        aliases:
          - pwn.csaw.io

networks:
  ctfnet:
    external: true
